nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']  # C'est l'URL de votre frontend React Js et React Native 8081
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'] # Méthodes autorisées
        expose_headers: []
        max_age: 3600
    paths: 
        '^/': ~ # Appliquer à toutes les routes
