security:
    firewalls:
        # Désactivation complète de la sécurité pour toutes les routes
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # Configuration de votre firewall principal
            pattern: ^/
            security: false

    access_control:
        # Autoriser toutes les routes
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
